### ISSUE TITLE
Missing delay option reads only one device

### ISSUE THREAD

**Issue by GreyPenguin** [geeks-r-us/SMI260#3]
Currently only one SMI260 can be queried as a delay is missing. If you want to read multiple devices you can add the following patch - which is basically just another wait after querying for the power status. All other stats are collected nicely only the generated power is updated on the first device.
diff --git a/src/SMI260MQTTGateway.py b/src/SMI260MQTTGateway.py
index da6065d..1c1f01d 100644
--- a/src/SMI260MQTTGateway.py
+++ b/src/SMI260MQTTGateway.py
@@ -132,6 +132,7 @@ class Communication(asyncio.Protocol):
                 await asyncio.sleep(0.15)
                 message = self.smi.query_settings(device)
                 self.transport.write(message)
+                await asyncio.sleep(0.15)
 
             await asyncio.sleep(self.state.poll_every)

**Comment by geeks-r-us** [comment]
fixed with 43190b83308c3abee4b2e95356dd3f10be7fb942
